### PR TITLE
140: Update session state update cases.

### LINKED ISSUE #140: Client settings doesn't show configured settings at the top bar.
Steps to reproduce:
1. Remove configured client settings. At the top should be written: "no configured settings".
2. Add some settings. The top bar stays unchanged, but it should show added settings.

Screenshot 2023-02-10 at 13 29 05
Screenshot 2023-02-10 at 13 28 59

### PR DESCRIPTION
**Pull request by DijanaPavlovic**
Resolves #140.

### CODE REVIEW

File: shared/studio/state/sessionState.ts [hunk 1]
```diff
@@ -283,7 +283,7 @@ export class SessionState extends Model({
       ? Object.entries(this.draftState.globals).some(([name, global]) => {
           const snap = this.draftSnapshot!.globals[name];
           return (
-            (!global.active && snap?.active) ||
+            (snap?.active && global.active !== snap.active) ||
```
Comment (jaclarke) [inline shared/studio/state/sessionState.ts:286]:
```suggestion
            (snap && global.active !== snap.active) ||
```

File: shared/studio/state/sessionState.ts [hunk 2]
```diff
@@ -342,6 +342,7 @@ export class SessionState extends Model({
 
   @action
   updateActiveState() {
+    console.log("update active state");
```
Comment (jaclarke) [inline shared/studio/state/sessionState.ts:345]:
```suggestion
```

**Review by jaclarke — APPROVED** [review]
